# usage: validate.sh calls.snp ground_truth.vcf ref.fasta out.txt

# calls.snp: calls generated by ebwt2snp
# ground_truth.vcf: vcf file containing ground truth
# ref.fasta: reference fasta file
# out.txt: output file with the report

# converts calls.snp into a vcf file and compares it to the ground truth

calls=$1
GT=$2
ref=$3
out=$4

echo "input calls: "$calls
echo "input ground truth: "$GT
echo "input reference: "$ref
echo "output report: "$out

seqtk seq -F 'h' $calls > $calls.fastq

if [ ! -f $ref.bwt ]; then
	bwa index $ref
fi

bwa mem $ref $calls.fastq -o $calls.sam

sam2vcf -f $ref -s $calls.sam -v $calls.vcf

vcf_vs_vcf -1 $calls.vcf -2 $GT > $out
